spring:
   application:
      name: "configserver"
   profiles:
      active: native
   cloud:
      config:
         server:
            git:
               search-locations: "https://github.com/mohdtausif/TinyBankMicroservicesDemo.git/configserver"
               default-label: master
               timeout: 5
               clone-on-start: true
               force-pull: true
               

logging:
   level:
      org:
         springframework: info
         
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

server:
  port: 8071